version: "3"
services:
  apache:
    build: 
      context: .
      dockerfile: ./docker/apache/Dockerfile
    ports:
      - 8080:80
    volumes:
      - type: bind
        source: ./apache/
        target: /usr/local/apache2/htdocs/
    restart: always
