version: '3'
services:
  jupyterlab:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    restart: always
    ports:
      - 8080:8080
    volumes:
      - type: bind
        source: ./src
        target: /usr/app/src