version: '3'
services:
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - 8080:80
    volumes:
      - type: bind
        source: ./nginx
        target: /usr/share/nginx/html
    restart: always

