version: "3"
services:
  react:
    build:
      context: .
      dockerfile: ./docker/react/Dockerfile
    ports:
      - 5050:3000
    volumes:
      - type: bind
        source: ./react
        target: /usr/src/app