version: "3"
services:
  springboot:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - 8080:8080
      # - 5050:5050
    tty: true
    restart: always
    volumes:
      - type: bind
        source: ./spring-boot-docker
        target: /usr/app