version: "3"
services:
  backend:
    build:
      context: .
      dockerfile: ./docker/flask/Dockerfile
    restart: always
    ports:
      - 5000:80
    volumes:
      - type: bind
        source: ./flask
        target: /usr/src/app