version: "3"
services:
  redmine:
    build:
      context: .
      dockerfile: ./docker/redmine/Dockerfile
    ports:
      - 8080:3000
    depends_on:
      - database
    restart: always
    environment:
      - REDMINE_DB_MYSQL=database
      - REDMINE_DB_DATABASE=redmine000db
      - REDMINE_DB_USERNAME=redmine000kun
      - REDMINE_DB_PASSWORD=rkunpass

  database:
    build: 
      context: .
      dockerfile: ./docker/mariadb/Dockerfile
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=mariarootpass
      - MYSQL_DATABASE=redmine000db
      - MYSQL_USER=redmine000kun
      - MYSQL_PASSWORD=rkunpass
    command: --character-set-server=utf8 --collation-server=utf8_general_ci --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
volumes:
  db_data: